# This file is part of: App-X11-Forward-PyCRust-Development-Template-Stack
# Copyright (c) 2024 Nico Jan Eelhart
#
# This source code is licensed under the MIT License found in the  'LICENSE.md' file in the root directory of this source tree.
#

# GOAL
# Combine Python, Rust and C/C++, to develop Desktop/Web application both for Linux and Windows (cross compiling)
# The Windows/Linux Desktop GUI is forwarded to the (Window) Host 
# 
# BEFORE executing the compose Docker command make sure you have read 'howto_create_a_dev_container.md' in the

networks:

# Define a network where the container has a fixed IP address
# bridge does not work on Docker Desktop(DD) with Windows containers, but works fine under DD with Linux containers
#
# When in the same network, using both the same 'nat' and 'bridge' setting, containers can communicate with each other via their
# the service names (x11_network-fixed in this case) or IP address, no port mappings needed for inter-container communication.
#
# You can replace 'nat', 'bridge' with 'overlay' which is meant for production clusters, load balancing (Docker Swarm or Kubernetes 
# deployments) For simple, local setups where multi-host communication is not needed, using overlay might be overkill.
# 
# See the file: '.env' for the variables
# docker network create external-example

  x11_forward-network-pycrust-fixed: 
    name: ext_x11_forward-network-pycrust-fixed
    driver: bridge 
    ipam:
      config:
        - subnet: ${FIXED_SUBNET}



volumes:
  vol_win32:
  

services:               
    axf-basic-pycrust-service:                    #  Our base service 
        build:
            context: .  
            dockerfile: Dockerfile_App-Forward-X11-PyCRust_Base
        image: eelhart/appforwardx11-pycrust-base:latest # This name can be used to extend or chain this image.
        networks:
            x11_forward-network-pycrust-fixed:
              ipv4_address: ${FIXED_IP}         # Use a fixed IP address for this container
        environment:
            - PORT=${PORT}                      # Pass variable from .env to PORT (1e), this is available in the 
                                                # container(ENV) and in dockerfile, during building after
                                                # defining: 'ARG PORT' in the docker file
            - DISPLAY=host.docker.internal:0    # THIS relays the linux output to vcxsrv(Xlaunch) Also added in the Docker file!   
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix     # MOUNTS the X11 socket GUI directory
        command: ["/bin/sh", "-c", "while sleep 1000; do :; done"]  


# To Start this container:
# docker-compose -f  compose_app_forward_x11_pycrust_base.yml up -d --build --force-recreate  --remove-orphans
                     